### ISSUE TITLE
404 in NPM?

### ISSUE THREAD

**Issue by kkzhang** [rmachielse/ember-enum#1]
when i run `ember install ember-enum`, an error raised. Did you removed it from npm?

**Comment by rmachielse** [comment]
@kkzhang well I never published it to npm because it's just a work in progress. Would you like to try it? The way to do that would be to add it to your package.json manually like this:

``` json
{
  "dependencies": {
    "ember-enum": "rmachielse/ember-enum"
  }
}
```

**Comment by panthony** [comment]
Would be nice to have a published tag though :)

**Comment by rmachielse** [comment]
@kkzhang @jholt1 @panthony well that's enough interest, I'll update and publish this addon soon!

**Comment by HerveSeger** [comment]
I am interested as well so please publish it in npm. 
It is a nice addon so don't be shy :)

**Comment by rmachielse** [comment]
@HerveSeger thanks for that haha. @kkzhang @jholt1 @panthony I have published it now, will do a new release with tests and demo page soon
